rapidsai/custrings

.gitmodules
=> Update to rmm 06

cpp/src/NVStringsImpl.cu
=> fixed null placement in from_strings

cpp/src/NVCategory.cu
=> allow for null category values

cpp/src/NVCategory.cu
=> alloc -1 for gather() pos values

cpp/include/NVStrings.h, cpp/python/pystrings.cpp, cpp/src/NVStrings_modify.cu, python/nvstrings.py, python/tests/test_substr.py
closes #147 
also reordered some of the declarations in the header -- to make it easier to find their implementations
=> added fillna

cpp/src/NVStrings_split.cu, python/tests/test_split_ws.py
=> split-ws var init corrected

CHANGELOG.md, ci/checks/style.sh, python/setup.py, python/setup_closed.py
also fixed some of the setup py files to pass flake8 style check
=> add flake8 checks for /python files

CHANGELOG.md, cpp/include/NVStrings.h, cpp/include/StringsStatistics.h, cpp/src/NVStrings.cu, cpp/tests/strstats.cu
Added only to C++ interface for now. Added test program to show it off.
=> compute character/string statistics

CHANGELOG.md, cpp/include/Rave.h, cpp/python/pyrave.cpp, cpp/src/Rave.cu, cpp/src/custring_view.cu, cpp/src/custring_view.cuh, python/rave.py, python/tests/test_rave.py
This is added to the rave module.
It accepts an nvstrings instance and then either a single target string or another nvstrings instance to compute the distance upon.
=> levenshtein edit-distance

CHANGELOG.md, cpp/src/NVStrings_convert.cu, python/nvstrings.py, python/tests/test_convert.py
Also rename `bools` to `booleans` in method names.
=> fix memory error in from_bools

CHANGELOG.md, conda/recipes/nvstrings/build.sh, cpp/CMakeLists.txt, cpp/Makefile.with_python, cpp/include/NVText.h, cpp/python/pytext.cpp, cpp/src/NVText.cu, python/nvtext.py, python/setup.py, python/setup_closed.py, python/tests/test_text.py
=> rename rave to nvtext

cpp/include/NVCategory.h, cpp/include/NVStrings.h, cpp/include/ipc_transfer.h, cpp/src/NVCategory.cu, cpp/src/NVStrings.cu, cpp/src/NVStringsImpl.cu, cpp/src/NVStringsImpl.h, cpp/tests/ipc_test.cu
=> added ipc_transfer methods to nvstrings

CHANGELOG.md, python/nvstrings.py
=> Fixed some pad examples in nvstrings.py doc comments

CHANGELOG.md, cpp/src/NVStrings_modify.cu, cpp/src/custring_view.cu
=> Allow insert on start=stop in replace

CHANGELOG.md, README.md
=> Fixing README link to python API docs

CHANGELOG.md, python/cpp/pystrings.cpp, python/nvstrings.py, python/tests/test_pad.py
=> Parameter check corrected for pad methods

CHANGELOG.md, ci/cpu/upload_anaconda.sh
=> [REVIEW] Fix definition of upload files for conda packages

CHANGELOG.md, cpp/src/NVStrings_modify.cu, cpp/src/util.cu, cpp/src/util.h, python/tests/test_regex.py
=> Fixed backref to continue replacing

CHANGELOG.md, cpp/CMakeLists.txt, cpp/include/ipc_transfer.h, cpp/src/NVCategory.cu, cpp/src/NVStringsImpl.h, cpp/src/custring.cuh, cpp/src/custring.inl, cpp/src/custring_view.cuh, cpp/src/custring_view.inl, cpp/src/regex/regex.cuh, cpp/src/regex/regexec.cpp, cpp/src/regex/regexec.inl, cpp/src/util.cu, cpp/src/util.h, cpp/src/util.inl, python/cpp/CMakeLists.txt
=> Convert device-only custring_view to header-only

CHANGELOG.md, cpp/doxygen/Doxyfile, cpp/include/NVCategory.h, cpp/include/NVStrings.h
=> Fixed doxygen formatting and updated to 0.7

CHANGELOG.md, cpp/include/NVStrings.h, cpp/src/NVStrings_modify.cu, python/cpp/pystrings.cpp, python/nvstrings.py, python/tests/test_substr.py
=> Allow nvstrings parameter to fillna

CHANGELOG.md, cpp/include/NVStrings.h, cpp/src/NVStrings_attrs.cu, python/cpp/pystrings.cpp, python/nvstrings.py, python/tests/test_convert.py
=> added is_empty method

CHANGELOG.md, cpp/include/NVStrings.h, cpp/src/NVStrings_array.cu, python/cpp/pystrings.cpp, python/nvstrings.py, python/tests/test_array.py
=> Support negative slicing

CHANGELOG.md, python/cpp/pytext.cpp
=> Fixed exception on invalid parameter to edit_distance

CHANGELOG.md, cpp/src/NVText.cu, python/tests/test_text.py
=> Fixed token_count counting empty string as token

CHANGELOG.md, cpp/include/NVStrings.h, cpp/src/NVStrings_modify.cu, cpp/src/custring_view.inl, python/cpp/pystrings.cpp, python/nvstrings.py, python/tests/test_substr.py
=> Added insert method as alternative to slice_replace insert

CHANGELOG.md, python/cpp/pystrings.cpp, python/nvstrings.py
=> Added get_info method to show data about strings

CHANGELOG.md, python/cpp/pystrings.cpp, python/nvstrings.py
Auto-merge triggered by push to `branch-0.4` that creates a PR to keep `branch-0.8` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> [gpuCI] Auto-merge branch-0.4 to branch-0.8 [skip ci]

CHANGELOG.md, cpp/src/NVStrings_pad.cu, python/cpp/pystrings.cpp
=> Check for empty fillchar in pad methods

CHANGELOG.md, CONTRIBUTING.md, ci/local/README.md, ci/local/build.sh
Local build script for developers to test their local repository in a gpuCI docker container.
=> [REVIEW] Add local build script to cuStrings [skip ci]

CHANGELOG.md, cpp/include/NVStrings.h, cpp/src/NVStrings_array.cu, python/cpp/pystrings.cpp, python/tests/test_array.py
=> [REVIEW] Added gather method for booleans array

CHANGELOG.md, ci/gpu/build.sh
Add junit output XML for pytest
=> [REVIEW] Add junit output to pytest

CHANGELOG.md, cpp/src/NVText.cu, python/nvtext.py, python/tests/test_text.py
=> updated nvtext.ngrams to call C++ method

CHANGELOG.md, ci/cpu/upload_anaconda.sh
=> [REVIEW] libnvstrings should always be labelled with main

CHANGELOG.md, cpp/src/NVStrings_find.cu, cpp/src/NVStrings_modify.cu, cpp/src/NVStrings_substr.cu, cpp/src/regex/regex.cuh, cpp/src/regex/regexec.cpp, cpp/src/regex/regexec.inl, python/cpp/pystrings.cpp
=> [REVIEW] Increased regex instruction threshold to 1024

CHANGELOG.md, cpp/src/NVStrings_convert.cu, python/tests/test_convert.py
=> [REVIEW] Fixed calculation error in ip2int

CHANGELOG.md, cpp/CMakeLists.txt, cpp/src/NVStrings_convert.cu, cpp/src/custring.inl, cpp/src/custring_view.cuh, cpp/src/custring_view.inl, python/tests/test_convert.py
=> [REVIEW] Support NaN, Inf strings in stof and stod

CHANGELOG.md, cpp/src/NVStrings_convert.cu, python/tests/test_convert.py
=> [REVIEW] Add .0 to integer output when using ftos/dtos

CHANGELOG.md, cpp/include/NVCategory.h, cpp/include/NVStrings.h, cpp/src/NVCategory.cu, cpp/src/NVStrings.cu, cpp/src/NVStringsImpl.cu, cpp/src/NVStringsImpl.h, python/cpp/pycategory.cpp, python/cpp/pystrings.cpp, python/nvcategory.py, python/nvstrings.py, python/tests/test_offsets.py
=> [REVIEW] Support device memory in from_offsets

CHANGELOG.md, Dockerfile
=> Fixed a flag which is necessary for conda install in Dockerfile

CHANGELOG.md, docs/source/_static/params.css, docs/source/conf.py
Fixes parameter formatting in python docs
=> [REVIEW] Fix python doc formatting [skip ci]

CHANGELOG.md, cpp/include/NVStrings.h, cpp/src/NVStrings_array.cu, python/cpp/pystrings.cpp, python/nvstrings.py, python/tests/test_array.py
=> [REVIEW] Added scatter method to nvstrings

README.md
Trivial update to readme to bump from 0.7 to 0.8
=> Update README.md to bump to 0.8

CHANGELOG.md, cpp/CMakeLists.txt, cpp/include/NVStrings.h, cpp/include/NVText.h, cpp/src/regex/regex.cuh, cpp/src/regex/regexec.inl, cpp/src/strings/NVStrings.cu, cpp/src/strings/NVStringsImpl.cu, cpp/src/strings/NVStringsImpl.h, cpp/src/strings/modify.cu, cpp/src/strings/replace_multi.cu, cpp/src/text/NVText.cu, cpp/tests/test_replace.cpp, python/cpp/pystrings.cpp, python/cpp/pytext.cpp, python/nvstrings.py, python/nvtext.py, python/tests/test_replace_multi.py, python/tests/test_substr.py
=> [REVIEW] Added replace() with multiple strings parameters

CHANGELOG.md, cpp/include/NVText.h, cpp/src/text/NVText.cu, cpp/tests/normalize_spaces.cpp, python/cpp/pytext.cpp, python/nvtext.py, python/tests/test_text.py
=> [REVIEW] Added normalize_spaces method to nvtext

CHANGELOG.md, python/cpp/pystrings.cpp, python/nvstrings.py, python/tests/test_memory.py
This pr adds python bindings for device memory and closes #362
=> Added python bindings for device memory
